name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actions:
    uses: typisttech/.github/.github/workflows/lint-actions.yml@84a542186b401cc272eeec5c9c077c3cb3c910e2 # v6.1.0
